### ISSUE TITLE
Mobile Optimizations

### ISSUE THREAD

**Issue by kiswa** [kiswa/vault#8]
Several things could be improved for the mobile layout.

* Keep ability to filter and sort
* Notifications need styling changes to always fit screen
* Lock header section in place?

**Comment by zakaryaasadi** [comment]
Hello Mr. Ross

Have a great day
I apologize for reaching you on github but couldn't find another option


I would like to negotiate with you about the Kiswa domain

If you are thinking of selling it, I will be very pleased

Please reply to my email, write any thing
zakaryaasadi@gmail.com

I will delete the comment soon
